title: Victor Alarcon
description: Artista visual, xilogravador, professor.
url: "https://ovictoralarcon.github.io"
baseurl: ""

author:
  name: Victor Alarcon
  email: contato@ovictoralarcon.com

whatsapp_numero: "11994906841"

# Build
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Collections
collections:
  obras:
    output: true
    permalink: /obras/:name/
  cursos:
    output: true
    permalink: /venha-pintar/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "obras"
    values:
      layout: "obra"

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - "*.git"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
